### ISSUE TITLE
Explanatory Agent returns blank knowledge graph on example query

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Explanatory-Agent#4]
When given the example query provided in the apidoc, explanatory agent returns no results.
```
{
  "message": {
    "query_graph": {
      "edges": [
        {
          "id": "e00",
          "source_id": "n00",
          "target_id": "n01",
          "type": "associated"
        }
      ],
      "nodes": [
        {
          "curie": "EFO:0004465",
          "id": "n00",
          "type": "disease"
        },
        {
          "id": "n01",
          "type": "gene"
        }
      ]
    }
  }
}
```

```
{
  "query_graph": {
    "edges": [
      {
        "id": "e00",
        "source_id": "n00",
        "target_id": "n01",
        "type": "associated"
      }
    ],
    "nodes": [
      {
        "curie": "EFO:0004465",
        "id": "n00",
        "type": "disease"
      },
      {
        "id": "n01",
        "type": "gene"
      }
    ]
  },
  "knowledge_graph": {
    "edges": [],
    "nodes": []
  },
  "results": []
}
```

**Comment by ehinderer** [comment]
I just spoke with our lead software engineer @tziomics. We believe the issue is that something changed with the KP that we query (the Genetics Provider). Not trying to pass the blame on, but we will look into it and try to get to the bottom of the issue.

**Comment by ehinderer** [comment]
@tziomics Can we confirm that this issue is resolved with the most recent integration efforts?

**Comment by tziomics** [comment]
@ehinderer The issue persists, but it is due to lack of data from the KP we are accessing to answer the query. If you send that query (or a v1.0 query) no results will return because we are not getting any results from Genetics Provider with that CURIE and predicate. It is not a problem with GP as a whole, as data is returned for other diseases (e.g. EFO:0000275).

Is the solution to change the apidoc example so it uses a CURIE that can return data or is EFO:0004465 expected to return data?
